# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ScoreBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScoreBoard
  pod 'Alamofire', '~> 5.4'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics', '~> 8.3.0'
  pod 'FirebaseUI/Auth'

  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/Facebook'
  #pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/Email'
  
  
  pod 'KeychainAccess'



end
